### ISSUE TITLE
MySQL database

### ISSUE THREAD

**Issue by Jaoheah** [WalshyDev/AutoCleanBot#1]
Hi,  I was wondering if you can tell me how to make a MySQL database I do not know how to.

**Comment by rolyd90** [comment]
I don't want to sound like a arse but use google.

Depending what OS you are installing it on the steps may be different. I have found searching 'digital ocean mysql' on google good for ubuntu tutorials.

For example: https://www.digitalocean.com/community/tutorials/a-basic-mysql-tutorial
There are steps to access the MySQL shell; where you can create a database after installation.

or on windows try using MySQL Workbench software; after you have installed MySQL Server.
