### ISSUE TITLE
An error occurred while creating the task!

### ISSUE THREAD

**Issue by atillayeet** [WalshyDev/AutoCleanBot#5]
I can't set up an autoclean. It says "An error occurred while creating the task!" everytime I try. Can you please tell me how to fix that?

**Comment by WalshyDev** [comment]
Can you please look in console and give me the exception it printed

**Comment by atillayeet** [comment]
how can I do that? I'm new to these things, sorry.

**Comment by WalshyDev** [comment]
Where you started the bot, look there and there should be a massive error thing. I need that.

**Comment by atillayeet** [comment]
![2018-03-23_23-20-33](https://user-images.githubusercontent.com/37707549/37851698-f29484fe-2ef0-11e8-8141-845e0d1ffea0.png)
In here or somewhere else? Because there isn't anything in here.

**Comment by helios4281** [comment]
hi,  can you help.  i got this error when i tried to run the bot... 
![image](https://user-images.githubusercontent.com/22951977/40126633-5768df20-58f3-11e8-9ecf-2be1979bc4df.png)

**Comment by WalshyDev** [comment]
@helios4281 Please make new issues rather than using old ones. Either way, you're running `java AutoCleanBot-1.0.jar` not `java -jar AutoCleanBot-1.0.jar`

**Comment by helios4281** [comment]
sorry, will do it next time... thanks also for the quick response..
